### ISSUE TITLE
Redmine 3.4 compatibility

### ISSUE THREAD

**Issue by rompic** [jbox-web/redmine_bootstrap_kit#10]
Is this plugin compatible to Redmine 3.4?
Thanks for the info!

**Comment by rompic** [comment]
looks good so far.

**Comment by n-rodriguez** [comment]
> Is this plugin compatible to Redmine 3.4?

Well it should be :)

**Comment by JanMalte** [comment]
@n-rodriguez Maybe you could update the Redmine Plugin Page:
https://www.redmine.org/plugins/redmine_bootstrap_kit
