### ISSUE TITLE
Help on using Redmine Bootstrap Kit

### ISSUE THREAD

**Issue by maheshassyst** [jbox-web/redmine_bootstrap_kit#2]
I have cloned  Redmine Bootstrap Kit in plugin folder in redmine.
I couldn't find any steps for using it, can you please help.

**Comment by n-rodriguez** [comment]
I've updated the README file. I'll add more informations later.
Note this is not a theme for Redmine but more a toolkit for plugin developers.

**Comment by maheshassyst** [comment]
Thanks for the quick response.
