### ISSUE TITLE
Missing release tag for 0.2.0?

### ISSUE THREAD

**Issue by mrueg** [jbox-web/redmine_bootstrap_kit#3]
https://jbox-web.github.io/redmine_git_hosting/howtos/migrate/#step-by-step-migration-from-0710-version-to-v100

The migration guide says

```
# Update Bootstrap Kit
redmine$ cd REDMINE_ROOT/plugins/redmine_bootstrap_kit
redmine$ git checkout v0.2.0
```

**Comment by mrueg** [comment]
The branch is there, but having a release tarball would be  great :)

**Comment by n-rodriguez** [comment]
> The branch is there, but having a release tarball would be great :)

Done!

**Comment by mrueg** [comment]
Thank you!
