### ISSUE TITLE
Error in redmine 3.0.3 undefined method `redmine_bootstrap_kit_load'

### ISSUE THREAD

**Issue by Zonork** [jbox-web/redmine_bootstrap_kit#8]
i install the plugin version 0.2.3

call the helper in my controller helper :redmine_bootstrap_kit

and call:  

<% content_for :header_tags do %>
  <%= redmine_bootstrap_kit_load(:redmine_bootstrap_kit) %>
  <%= redmine_bootstrap_kit_load(:bootstrap_alerts) %>
  <%= redmine_bootstrap_kit_load(:bootstrap_label) %>
  <%= redmine_bootstrap_kit_load(:bootstrap_modals) %>
  <%= redmine_bootstrap_kit_load(:bootstrap_switch) %>
  <%= redmine_bootstrap_kit_load(:bootstrap_tables) %>
  <%= redmine_bootstrap_kit_load(:jquery_tag_it) %>
  <%= redmine_bootstrap_kit_load(:font_awesome) %>
<% end %> 

in my views. but i have this error:

undefined method `redmine_bootstrap_kit_load'

**Comment by Zonork** [comment]
Where you define "redmine_bootstrap_kit_load" method?

**Comment by n-rodriguez** [comment]
> Where you define "redmine_bootstrap_kit_load" method?

Actually nowhere. I'm really sorry, the README is not up to date.

**Comment by n-rodriguez** [comment]
Doc updated : https://github.com/jbox-web/redmine_bootstrap_kit#how-to-use
